[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""  # Let Dockerfile CMD handle this
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
LANGFLOW_DATABASE_URL = "${{DATABASE_URL}}"
RAILWAY_VOLUME_MOUNT = "/data" 